[build]
  cmd = "go build -o ./tmp/main ."
  bin = "tmp/main"
  full_bin = ""
  delay = 1000  # milliseconds
  exclude_dir = ["tmp", "vendor"]
  include_ext = ["go", "tpl", "tmpl", "html", "env"]
  exclude_file = []
  follow_symlink = false
  log = "air.log"
  send_interrupt = true
  stop_on_error = true
  kill_delay = "0s"

[log]
  time = true

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta"
  error = "red"

[misc]
  clean_on_exit = true